---
deployment:
  tasks:
    - export DEPLOYPATH=/home/demodepl/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH

